---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    app: load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
        - image: k8s.gcr.io/hpa-example
          name: load-test
          ports:
            - name: web
              containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-test
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: load-test
spec:
  selector:
    app: load-test
  ports:
    - port: 80
      targetPort: web

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: load-test
spec:
  entryPoints: # We listen to requests coming from ports 80 and 443
    - web
    - websecure
  routes:
    - match: Host(`load.wam.localhost`)
      kind: Rule
      services:
        - name: load-test # Requests will be forwarded to this service
          port: 80
  tls:
    secretName: load.wam.localhost

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: load.wam.localhost
spec:
  dnsNames:
    - load.wam.localhost
  secretName: load.wam.localhost
  issuerRef:
    name: selfsigned # Use the issuer created previously
    kind: ClusterIssuer
