apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-auth
  namespace: traefik-system
spec:
  encryptedData:
    auth.txt: AgAgC/9JhpD0/c3pH5jqOo8YhVYC0weOIoCqMKfmVrs6ARzpV/dLYkvyfIPlcFP8IOVf7Z4p4cZ/Bu/qyROYOLuwUwkZrP9Wvag4MsfIc0zF8FZnKWRz94kR2Iu7MVn1TQYkPDAvZxIpe5ADfxkPOeflIfZi2Y6ZgLYpeF4gF5PWcqTfU1wlBXexRIPyUUfVCR9SAq8hMBRU9v+r2PLLsTQhkvdqlhSC4JLF4aQbCb8H0zMD7JBjNkBTTvaGtN/IZ9/px3ht031p0HqJjiHMsLU2zhmoQtMcXGxWvSbJc/3edHXMZ+Otz+B8vNqUUuw//uk1ya1WgRX911Ltfh4/S99i8ClLzfWEURVcpxPELFY8n4SiNitN8LRTBsttJPhcoPcjgtYacEyXtDRZWno9z8r3OrlYQNkEFP68cLgy0i+BaniOAbOmnHcL26TCg6qFkd5m7D4PCxKGQSQhmCPQfrxXltSHDDRIf7Myd4RvDEIm/2jQAQ3GKF74Q9oPA39+eEAGvv8wdWXBQ+GRb9+tkuN/MuiyHJA93GwmNR8efTuRlBfFLDq72BnWchpCeYU3OV1z1nVi5INbRYc81N4zT5WPMXg7K4Rz3joHW2BFnqsXkCndy8MNJavut4hzHZx6KZYLUUyUVIrOJwqRHVBSZirJmjIawdQPi2YKBhikOa5J59cS9jm8aUPjFjxn+wmCZ+gt93s8R6lAJxuio+FcoT7J6xfQic4Fl+qNwh1aElZN++CDjO64UML3pjs=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-auth
      namespace: traefik-system

