apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-auth
  namespace: traefik-system
spec:
  encryptedData:
    auth.txt: AgCBh8q9cKNSXPyAoE4M4W3pcDl+ZsLfvbF26Kg8fS4LxQjGCJKHAyrPbdRIqGPD7bPQgv/wpClZdnmjgODU91lCw4JXat/XPddGePzYLtSXL4tdl3SZXYtLm2nnSIxzkFDfT/gYHaZEa7t82dxSUO9cMmBdF1wgoSMBzP6fr9wBjrIc1yp24YquHSy0QVWbcJxmq7KpcV2RIYTpef8uQ3gHUXejJUvxSYRQq52ohpKRigwx87gTDj7eYtGKRSAzaJEYqz70ix7RyNJlsULC62z7YrTn1VGVuq2qfbRYNcLZfMoU31VfnoBgWb0yTf8C167XhK3ZhLj2bB/a800iTgEp+CMku5UuH3OpwJKqb/C1dFypw95qD2LhWKxnI7/P/KzsQf8hK7QjYDz/4ceXsstM4kFX/JwjTKXaXNT9jSDgtjqPg6F+n5feOKfhrHUL1+Vh2oKPm/IoIECAoXAqFsihs0un/HrKexkZdxtWYiGDtbydwMebgnEvsBpZ3SCS4itUpPseqUXY/8xdyFZbvYxfj4b/oOi1cM7gBvHPcA9RMJqNF/2n93KrkGy/nbVIv8RO3e3pC10DB/nvdkZhbHx+FiEKU1FvB6QJ9UOQrk+IDCj8DMrBNlRN6kCcNjZrusUoSgagrH+U3ISMe1YpQ6B6YNskXBkk4Z0M6RTIJn459IfKeAwpNJ+cfZcvsOxu7Poc5fHoIuYSuoQbdnTGnoQGqIdUWQZ0zErM8ZRTB9YfQgIJI02Ui2O7u74=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-auth
      namespace: traefik-system

