apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-auth
  namespace: traefik-system
spec:
  encryptedData:
    auth.txt: AgCCrXhfiatiURngnpPDabxj/IhsPR+jnjOXiG30Xobru1u3HjBPerQgq922zFOf2JBS83hIGiBbAbr5ciLSA0NqeX/mLASLN1m3xdf7y5QNDgg8IpuQ3DeD0dcKn3HtD6gJqhjkuioZBBUJDNO+Bbxf0iwjfNMEWRWs+xxbOJIDbb4b+E2DkKgh8NDE1HoS4zHM0f6BTvbQ5FxPY1bRHemxCPhDFLtLRuDyP2EgXCsZUFTrdP1sDm3nrT7mBus/2QZRuFz5/ZvJ5gylDPfk7agELQ1ky6b9qKvEXledQhue7n2mdTlYORFGuh+Rl5WKisgdHju84Pr5IEQUOAy0q5zwFEu82ZygP9cwH9mRUcgVIuGBubgWdeQAwB+TxSmpgTV0I7CYNxvN5J3s7QAlzVFBQqi4QELS8hnHeSikv+eT2DHLve6H1/RrCy1IhqM5b2dZgr4hBv/C4OW89fFasDxMKcX8WikKIj8VSDZWn/rpVCGE7TytwNZUEUwAJefC7YYGjO5UFEP9UnoMGbbuSSQfsCldQDDjcLp1j5Gk+wn7/zhK1pEJxYCe9d/YbKyPlZjM9JPnMPSRs7RKoAJdpEY326f30SbYYdfnN610HH20vJE3rm7Y870tYHqNVm9NfuEuGNx+hA7/4cAt0wX9R5jYDNBf5cdqTBDYFginLN6p8NhCwc4MOwW9x8cRfTTXK8GSVNL9KgUayAY9VOGRU8NCBCelemqNTUinTmV6hKUIRvHpvJfvnvl9r48=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-auth
      namespace: traefik-system

