apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-admin
  namespace: monitoring
spec:
  encryptedData:
    TRAEFIK_PASSWORD: AgACy/z7GuZe85nmn63uaqJHnL05rdcO8EC2vwn7qDg7qO01v/o4C1QZUuP4G1nU/zZTk/6Ypebq+a3EQmJ+Ypx3+31zgQddKiHKLvAEvV89IDA7heZoKEX2/9C8CMPSlCv2yevyOp37CRWoGuui+IKWmMzm9Ulo8UOMMmulc41lbFSbsqBDnDfYHFVQxLouEbBwb4Thn8jwsIZ1i0KR0UeFdKQzDLBXC3X9ruASEbXQYxUQqVSd0mvyXUgcp2vyW81f0AjnAVc/ebus6c+kOCzxIyrIe+WuG8ghhjvpFU/STlm5C5zKWfR6hnBn2FPaxS3rg9HBddGFK+4XEUSLg4Lidxo5IMrWSz+fcpkANCiGFSyb5eaYUg26SjlEOP5/rrt8Q5amMWjoLpJu0ykG1cWFc2bRhhk21AhjpGwVvBeZ7B9JhLVsSOseJWXfIpXEG0WZ6ivOyseBZ73q/9twHeIXGke8SntEee5Uy3oM+fCM07dYJublAq2qdoPpd03j5MAKjDojAUodGmjQg2sDJemMFZipeEb916HRGft0c9BL2GK0arNg4kryt6kC5hs1RI/h2hvnHlzpwHQfLxZ11XKEVyzFtqYOQ8YUi8GDduRiZr46pc+T9qFc1oSU3NUhTyDz2C73gTDMwt92yIAtGiEobAT0lHAaSPPxwWqx3bsfPI/RAw57aDgA+DvApxamwMHJ/LBrPlY=
    TRAEFIK_USER: AgCX4TxbECYGLr3ukWGOXX/wmM6L2ncVQLM7L+h45GAwhzXifkq415X0MgxWoh9UjQEzFAZ+Dw4Wev5nNcMCQX/71W/ijdg2kErjX+2b82rM/tROqWWgh5Qy5OCxZao9skOUzTaXEOCpKIYUoLJLzGvVL+FFvcdyLov6ylV0OnO0JRvz1IBPpa9w0CshPw/MaIUNF0EjCO8zWQGQXUEGqJdrwZyXoOxHQEOVytIwZtZcb1zKMInkcvTEbvpSIHjcGjw4DbCvTD1c4zd39Ou+7PEciEIQ3ee7s8JnQ20HMvv6W7Vqri5g6ApZ4pgCr1f5N74hwBBqATyux9TLvM02qqhoRSRZeoZgz7OtMKI4YIGeiwTqNu9cYhF+yAqx0GrDTYJPNZtzG8ruzqvAVVUoCrmuu/SH20chWn6jCo2KGSkXBlwAKHKTXQVg/aDqC9HxNWKA3rmxn5zsoAv5MLfrLRHvL4lWX/jS0kabjV5pJPs7tyXzlcJ0He4+39ju3Vw0G2nnSY3dGbb/ioay6GuXyCB4I54Pw74b/8MFxABenerYmbhROG1rxqIuWXmL3/mQQ7CVaNACwWowh8cFwuVE95LnT4qYf194adcREk98sT5mELsTuFQFtTJ3haWdqV7wYHCdZVaeMv7skAc9ec33NulIU+BSnqP7Khgn6T+3gPXSUtnrozvePtW0l43kFZoJoApT07s=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: monitoring-admin
      namespace: monitoring

