on: [push]

jobs:
  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac

    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.29.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

  terrascan-tf:
    runs-on: ubuntu-latest
    name: terrascan-tf
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - name: Run Terrascan IaC
        id: terrascan-iac
        uses: accurics/terrascan-action@main
        with:
          iac_type: "terraform"
          iac_version: "v14"
          iac_dir: "iac/"
          policy_type: "all"
          only_warn: true
  terrascan-k8s:
    runs-on: ubuntu-latest
    name: terrascan-k8s
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - name: Run Terrascan k8s
        id: terrascan-k8s
        uses: accurics/terrascan-action@main
        with:
          iac_type: "k8s"
          iac_version: "v1"
          iac_dir: "modules/"
          policy_type: "all"
          only_warn: true