on: [push]

jobs:
  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac

    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.29.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

  terrascan_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          iac_type: "terraform"
          iac_version: "v14"
          policy_type: "all"
          only_warn: true
